# Generated by Django 4.2.20 on 2025-04-26 14:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('Location', models.CharField(max_length=255)),
                ('services_type', models.CharField(choices=[('Wedding Videography', 'Wedding Videography'), ('Commercial Production', 'Commercial Production'), ('Music Videos', 'Music Videos'), ('Documentary', 'Documentary')], max_length=50)),
                ('booking_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('D', 'Completed'), ('X', 'Cancelled')], default='P', max_length=1)),
                ('project_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_details', to='bookings.clients')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_details', to='accounts.photographer')),
            ],
            options={
                'ordering': ['-event_date', '-event_time'],
            },
        ),
    ]
